[ENH] wrap a PSD estimation method around scipy.signal.welch
aeon-toolkit/aeon-neuro pull request #48
Opened 2024-06-18 16:52 UTC by futuer-szd

wrap a PSD estimation method around scipy.signal.welch, 
and write test for it, 
(but there is no 'aeon.testing.data_generation' module 
in the lastest version of aeon-neuro)

#### Any other comments?

I cannot find **PCASeriesTransformer** [aeon/aeon/transformations/series/_pca.py](https://github.com/aeon-toolkit/aeon/blob/f0a1b22cbb00207e75e1b5bc9429df05d962bb56/aeon/transformations/series/_pca.py) in the init [aeon/aeon/transformations/series/__init__.py](https://github.com/aeon-toolkit/aeon/blob/f0a1b22cbb00207e75e1b5bc9429df05d962bb56/aeon/transformations/series/__init__.py).

2024-06-20 06:23 UTC, futuer-szd commented
I think it is wrong or not complete. We want PSD matrics to calculate Riemannian distance, but we got just a number from this implementation.

2024-06-21 09:37 UTC, TonyBagnall requested changes

2024-06-21 09:37 UTC, TonyBagnall commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +        freqs = np.array(freqs)
may as well store them for now

self.freq_  = freq

2024-06-21 09:37 UTC, TonyBagnall commented on aeon_neuro/_wip/transformations/series/tests/test_psd_welch.py
> +def test_pca():
test_psd not pca

add a test of expected values

2024-06-21 09:37 UTC, TonyBagnall commented on aeon_neuro/_wip/transformations/series/tests/test_psd_welch.py
> +def test_pca():
from aeon.datasets import load_basic_motions

X, _ = load_basic_motions(split="Train")
do the transform on X[0]

find correct answer for X[0], first five values
expected = [ ...]
test correctness on these 
actual = [...]

2024-06-24 10:58 UTC, MatthewMiddlehurst reviewed
Looks fine structurally. A few comments.

2024-06-24 10:58 UTC, MatthewMiddlehurst commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +__maintainer__ = [""]
if there is no maintainer the list should be empty

2024-06-24 10:58 UTC, MatthewMiddlehurst commented on aeon_neuro/_wip/transformations/series/tests/test_psd_welch.py
> +__maintainer__ = [""]
same here

2024-06-24 10:58 UTC, MatthewMiddlehurst commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +        freqs = []
This does not seem to be used?

2024-06-24 10:58 UTC, MatthewMiddlehurst commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +        "capability:multivariate": True,
Do we want this to be multivariate capable if it is simply looping over the function? May be sensible in this case, but just a thought.

2024-06-24 12:05 UTC, futuer-szd commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +        "capability:multivariate": True,
I previously thought that multivariate means the ability to directly process data in the format (n_channels, n_timepoints), and indeed scipy.signal.welch has this capability without needing to loop. This loop was redundant. However, we need to calculate interactions between different channels, which requires further learning and implementation on my part.

2024-06-24 14:05 UTC, closed without merging

2024-06-24 14:17 UTC, MatthewMiddlehurst commented on aeon_neuro/_wip/transformations/series/_psd_welch.py
> +        "capability:multivariate": True,
Just a query, I dont know enough about the function currently yo answer really 🙂. The multivariate capability is the ability to process data with more than 1 channel.